/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Veotek
 */
public class Lab extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    ResultSet rs;
    Date date;
    /**
     * Creates new form Lab
     */
    public Lab() {
        initComponents();
        connect();
    }
    
    public void connect(){
        try {
            String host = "jdbc:mysql://localhost:3306/labveotek";
            //String host = "jdbc:mysql://localhost:3307/labveotek";
            //String host = "jdbc:mysql://localhost:3306/inventario1";
            String user = "root";
            String pwd = "veotek";
            
            con = DriverManager.getConnection(host, user, pwd);
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
            String query = "select * from pedido";
            rs = stmt.executeQuery(query);
            rs.next();
            idv.setVisible(false);
            int id= rs.getInt("idp");
            idv.setText(Integer.toString(id));
            int fol = rs.getInt("folio");
            String f = Integer.toString(fol);
            folio.setText(f);
            int refe = rs.getInt("ref");
            String r = Integer.toString(refe);
            referencia.setText(r);
/*            Date date = Calendar.getInstance().getTime();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String resultDate = fmt.format(date);
            fecha.setText(resultDate);*/
            String date = rs.getString("fecha");
            fecha.setText(date);
            String tec = rs.getString("tecnico");
            if(!tec.isEmpty())t.setText(tec);
            else t.setText("");
            String arm = rs.getString("armazon");
            if(!arm.isEmpty()) armazon.setText(arm);
            else armazon.setText("");
            String mic = rs.getString("micas");
            if(!mic.isEmpty())m.setText(mic);
            else m.setText("");
            String material = rs.getString("materiales");
            if(!material.isEmpty())mat.setText(material);
            else mat.setText("");
            String tratamiento = rs.getString("tratamiento");
            if(!tratamiento.isEmpty())trat.setText(tratamiento);
            else trat.setText("");
            String tipo = rs.getString("tipo");
            if(!tipo.isEmpty())ti.setText(tipo);
            else ti.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        materiales = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tratamiento = new javax.swing.JComboBox();
        tipo = new javax.swing.JComboBox();
        folio = new javax.swing.JFormattedTextField();
        tecnico = new javax.swing.JComboBox();
        referencia = new javax.swing.JFormattedTextField();
        fecha = new javax.swing.JFormattedTextField();
        micas = new javax.swing.JComboBox();
        t = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        mat = new javax.swing.JLabel();
        trat = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        primero = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        idv = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        armazones = new javax.swing.JComboBox();
        armazon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numFolio = new javax.swing.JFormattedTextField();
        numRef = new javax.swing.JFormattedTextField();
        BuscarFolio = new javax.swing.JButton();
        buscarRef = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dbupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Folio");

        jLabel2.setText("Ref");
        jLabel2.setName("Ref"); // NOI18N

        jLabel3.setText("Fecha");

        jLabel4.setText("Tecnico");

        jLabel5.setText("Micas");

        jLabel6.setText("Materiales");

        materiales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CR-39", "Poly", "Hi-Index", "Cristal" }));

        jLabel7.setText("Tratamiento");

        jLabel8.setText("Tipo");

        tratamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BCO", "Antireflejante", "Fotocromatico", "Transitions", "Crizal", "Transitions-Crizal", "AR-Foto", "Polarizado", "Polarizado-AR" }));

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terminado", "Procesado", "Rebisel" }));

        folio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        folio.setEnabled(false);

        tecnico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Francisco", "Sergio", "Angel", "Jesus" }));

        referencia.setEnabled(false);

        fecha.setEnabled(false);

        micas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monofocal", "Progresivo", "Flat-Top", "Blend" }));

        t.setText("jLabel9");

        m.setText("jLabel10");

        mat.setText("jLabel11");

        trat.setText("jLabel12");

        ti.setText("jLabel13");

        primero.setText("Primer Registro");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });

        anterior.setText("Anterior Registro");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente Registro");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        ultimo.setText("Último registro");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar registro");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        idv.setToolTipText("");
        idv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idv.setEnabled(false);

        jLabel9.setText("Armazones");

        armazones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Completos", "Ranurados", "3 Piezas" }));

        armazon.setText("jLabel10");

        jLabel10.setText("Folio");

        jLabel12.setText("Referencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        BuscarFolio.setText("Buscar Folio");
        BuscarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarFolioActionPerformed(evt);
            }
        });

        buscarRef.setText("Buscar referencia");
        buscarRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRefActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Veotek\\Pictures\\veotek-min.png")); // NOI18N

        dbupdate.setText("Actualizar base de datos");
        dbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numRef, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(numFolio))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarFolio)
                    .addComponent(buscarRef)
                    .addComponent(dbupdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(482, 482, 482))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(referencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(micas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(m)
                                    .addComponent(primero)))
                            .addComponent(idv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7))
                            .addComponent(mat)
                            .addComponent(anterior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(siguiente)
                                .addGap(18, 18, 18)
                                .addComponent(ultimo)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(actualizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addComponent(trat))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ti)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(armazones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(armazon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t)
                    .addComponent(jLabel9)
                    .addComponent(armazones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(armazon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(micas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m)
                    .addComponent(mat)
                    .addComponent(trat)
                    .addComponent(ti))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primero)
                    .addComponent(anterior)
                    .addComponent(siguiente)
                    .addComponent(ultimo)
                    .addComponent(actualizar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarFolio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarRef))
                        .addGap(18, 18, 18)
                        .addComponent(dbupdate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRefActionPerformed
        // TODO add your handling code here:
        String r = numRef.getText();
        if(r.isEmpty()){
            JOptionPane.showMessageDialog(this, "Referencia no recibida");
        }
        else{
            try{
                String query = "select * from pedido where ref = "+r;
                rs = stmt.executeQuery(query);
                rs.next();
                idv.setVisible(false);
                int id= rs.getInt("idp");
                idv.setText(Integer.toString(id));
                //int fol = rs.getInt("folio");
                //String f = Integer.toString(fol);
                int f = rs.getInt("folio");
                folio.setText(Integer.toString(f));
                //int refe = rs.getInt("ref");
                //String r = Integer.toString(refe);
                referencia.setText(r);
                /*            Date date = Calendar.getInstance().getTime();
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                String resultDate = fmt.format(date);
                fecha.setText(resultDate);*/
                String date = rs.getString("fecha");
                fecha.setText(date);
                String tec = rs.getString("tecnico");
                if(!tec.isEmpty())t.setText(tec);
                else t.setText("");
                String arm = rs.getString("armazon");
                if(!arm.isEmpty()) armazon.setText(arm);
                else armazon.setText("");
                String mic = rs.getString("micas");
                if(!mic.isEmpty())m.setText(mic);
                else m.setText("");
                String material = rs.getString("materiales");
                if(!material.isEmpty())mat.setText(material);
                else mat.setText("");
                String tratamiento = rs.getString("tratamiento");
                if(!tratamiento.isEmpty())trat.setText(tratamiento);
                else trat.setText("");
                String tipo = rs.getString("tipo");
                if(!tipo.isEmpty())ti.setText(tipo);
                else ti.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_buscarRefActionPerformed

    private void BuscarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarFolioActionPerformed
        // TODO add your handling code here:
        String f = numFolio.getText();
        if(f.isEmpty()){
            JOptionPane.showMessageDialog(this, "Folio no recibido");
        }
        else{
            try{
                String query = "select * from pedido where folio = "+f;
                rs = stmt.executeQuery(query);
                rs.next();
                idv.setVisible(false);
                int id= rs.getInt("idp");
                idv.setText(Integer.toString(id));
                //int fol = rs.getInt("folio");
                //String f = Integer.toString(fol);
                folio.setText(f);
                int refe = rs.getInt("ref");
                String r = Integer.toString(refe);
                referencia.setText(r);
                /*            Date date = Calendar.getInstance().getTime();
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                String resultDate = fmt.format(date);
                fecha.setText(resultDate);*/
                String date = rs.getString("fecha");
                fecha.setText(date);
                String tec = rs.getString("tecnico");
                if(!tec.isEmpty())t.setText(tec);
                else t.setText("");
                String arm = rs.getString("armazon");
                if(!arm.isEmpty()) armazon.setText(arm);
                else armazon.setText("");
                String mic = rs.getString("micas");
                if(!mic.isEmpty())m.setText(mic);
                else m.setText("");
                String material = rs.getString("materiales");
                if(!material.isEmpty())mat.setText(material);
                else mat.setText("");
                String tratamiento = rs.getString("tratamiento");
                if(!tratamiento.isEmpty())trat.setText(tratamiento);
                else trat.setText("");
                String tipo = rs.getString("tipo");
                if(!tipo.isEmpty())ti.setText(tipo);
                else ti.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_BuscarFolioActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        int identificador = Integer.parseInt(idv.getText());
        String tec = tecnico.getSelectedItem().toString();
        String a = armazones.getSelectedItem().toString();
        String mc = micas.getSelectedItem().toString();
        String mats = materiales.getSelectedItem().toString();
        String tratmto = tratamiento.getSelectedItem().toString();
        String tp = tipo.getSelectedItem().toString();
        try{
            rs.updateString("tecnico", tec);
            rs.updateString("armazon", a);
            rs.updateString("micas", mc);
            rs.updateString("materiales",mats);
            rs.updateString("tratamiento", tratmto);
            rs.updateString("tipo", tp);
            rs.updateRow();
            JOptionPane.showMessageDialog(this, "Información Actualizada");

            String query = "select * from pedido";
            rs = stmt.executeQuery(query);
            rs.next();
            idv.setVisible(false);
            int id= rs.getInt("idp");
            idv.setText(Integer.toString(id));
            int fol = rs.getInt("folio");
            String f = Integer.toString(fol);
            folio.setText(f);
            int refe = rs.getInt("ref");
            String r = Integer.toString(refe);
            referencia.setText(r);
            /*            Date date = Calendar.getInstance().getTime();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String resultDate = fmt.format(date);
            fecha.setText(resultDate);*/
            String date = rs.getString("fecha");
            fecha.setText(date);
            tec = rs.getString("tecnico");
            if(!tec.isEmpty())t.setText(tec);
            else t.setText("");
            String arm = rs.getString("armazon");
            if(!arm.isEmpty()) armazon.setText(arm);
            else armazon.setText("");
            String mic = rs.getString("micas");
            if(!mic.isEmpty())m.setText(mic);
            else m.setText("");
            String material = rs.getString("materiales");
            if(!material.isEmpty())mat.setText(material);
            else mat.setText("");
            String tratamiento = rs.getString("tratamiento");
            if(!tratamiento.isEmpty())trat.setText(tratamiento);
            else trat.setText("");
            String tipo = rs.getString("tipo");
            if(!tipo.isEmpty())ti.setText(tipo);
            else ti.setText("");

        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
        try{
            int id= rs.getInt("idp");
            rs.last();
            int fol = rs.getInt("folio");
            String f = Integer.toString(fol);
            folio.setText(f);
            int refe = rs.getInt("ref");
            String r = Integer.toString(refe);
            referencia.setText(r);
            /*Date date = Calendar.getInstance().getTime();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String resultDate = fmt.format(date);
            fecha.setText(resultDate);*/
            String date = rs.getString("fecha");
            fecha.setText(date);
            String tec = rs.getString("tecnico");
            if(!tec.isEmpty())t.setText(tec);
            else t.setText("");
            String arm = rs.getString("armazon");
            if(!arm.isEmpty()) armazon.setText(arm);
            else armazon.setText("");
            String mic = rs.getString("micas");
            if(!mic.isEmpty())m.setText(mic);
            else m.setText("");
            String material = rs.getString("materiales");
            if(!material.isEmpty())mat.setText(material);
            else mat.setText("");
            String tratamiento = rs.getString("tratamiento");
            if(!tratamiento.isEmpty())trat.setText(tratamiento);
            else trat.setText("");
            String tipo = rs.getString("tipo");
            if(!tipo.isEmpty())ti.setText(tipo);
            else ti.setText("");

        }catch(SQLException e){
            JOptionPane.showMessageDialog(Lab.this, e.getMessage());
        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.next()){
                int id= rs.getInt("idp");
                int fol = rs.getInt("folio");
                String f = Integer.toString(fol);
                folio.setText(f);
                int refe = rs.getInt("ref");
                String r = Integer.toString(refe);
                referencia.setText(r);
                /*Date date = Calendar.getInstance().getTime();
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                String resultDate = fmt.format(date);
                fecha.setText(resultDate);*/
                String date = rs.getString("fecha");
                fecha.setText(date);
                String tec = rs.getString("tecnico");
                if(!tec.isEmpty())t.setText(tec);
                else t.setText("");
                String arm = rs.getString("armazon");
                if(!arm.isEmpty()) armazon.setText(arm);
                else armazon.setText("");
                String mic = rs.getString("micas");
                if(!mic.isEmpty())m.setText(mic);
                else m.setText("");
                String material = rs.getString("materiales");
                if(!material.isEmpty())mat.setText(material);
                else mat.setText("");
                String tratamiento = rs.getString("tratamiento");
                if(!tratamiento.isEmpty())trat.setText(tratamiento);
                else trat.setText("");
                String tipo = rs.getString("tipo");
                if(!tipo.isEmpty())ti.setText(tipo);
                else ti.setText("");
            }else{
                rs.previous();
                JOptionPane.showMessageDialog(Lab.this, "Fin de los registros");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(Lab.this, e.getMessage());
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.previous()){
                int id= rs.getInt("idp");
                int fol = rs.getInt("folio");
                String f = Integer.toString(fol);
                folio.setText(f);
                int refe = rs.getInt("ref");
                String r = Integer.toString(refe);
                referencia.setText(r);
                /*                Date date = Calendar.getInstance().getTime();
                SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
                String resultDate = fmt.format(date);
                fecha.setText(resultDate);*/
                String date = rs.getString("fecha");
                fecha.setText(date);
                String tec = rs.getString("tecnico");
                if(!tec.isEmpty())t.setText(tec);
                else t.setText("");
                String arm = rs.getString("armazon");
                if(!arm.isEmpty()) armazon.setText(arm);
                else armazon.setText("");
                String mic = rs.getString("micas");
                if(!mic.isEmpty())m.setText(mic);
                else m.setText("");
                String material = rs.getString("materiales");
                if(!material.isEmpty())mat.setText(material);
                else mat.setText("");
                String tratamiento = rs.getString("tratamiento");
                if(!tratamiento.isEmpty())trat.setText(tratamiento);
                else trat.setText("");
                String tipo = rs.getString("tipo");
                if(!tipo.isEmpty())ti.setText(tipo);
                else ti.setText("");
            }else{
                rs.next();
                JOptionPane.showMessageDialog(Lab.this, "Fin de los registros");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(Lab.this, e.getMessage());
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        // TODO add your handling code here:
        try{
            int id= rs.getInt("idp");
            rs.first();
            int fol = rs.getInt("folio");
            String f = Integer.toString(fol);
            folio.setText(f);
            int refe = rs.getInt("ref");
            String r = Integer.toString(refe);
            referencia.setText(r);
            /*Date date = Calendar.getInstance().getTime();
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String resultDate = fmt.format(date);
            fecha.setText(resultDate);*/
            String date = rs.getString("fecha");
            fecha.setText(date);
            String arm = rs.getString("armazon");
            if(!arm.isEmpty()) armazon.setText(arm);
            else armazon.setText("");
            String tec = rs.getString("tecnico");
            if(!tec.isEmpty())t.setText(tec);
            else t.setText("");
            String mic = rs.getString("micas");
            if(!mic.isEmpty())m.setText(mic);
            else m.setText("");
            String material = rs.getString("materiales");
            if(!material.isEmpty())mat.setText(material);
            else mat.setText("");
            String tratamiento = rs.getString("tratamiento");
            if(!tratamiento.isEmpty())trat.setText(tratamiento);
            else trat.setText("");
            String tipo = rs.getString("tipo");
            if(!tipo.isEmpty())ti.setText(tipo);
            else ti.setText("");

        }catch(SQLException e){
            JOptionPane.showMessageDialog(Lab.this, e.getMessage());
        }
    }//GEN-LAST:event_primeroActionPerformed

    private void dbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbupdateActionPerformed
        // TODO add your handling code here:
        connect();
    }//GEN-LAST:event_dbupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarFolio;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton anterior;
    private javax.swing.JLabel armazon;
    private javax.swing.JComboBox armazones;
    private javax.swing.JButton buscarRef;
    private javax.swing.JButton dbupdate;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JFormattedTextField folio;
    private javax.swing.JLabel idv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel m;
    private javax.swing.JLabel mat;
    private javax.swing.JComboBox materiales;
    private javax.swing.JComboBox micas;
    private javax.swing.JFormattedTextField numFolio;
    private javax.swing.JFormattedTextField numRef;
    private javax.swing.JButton primero;
    private javax.swing.JFormattedTextField referencia;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel t;
    private javax.swing.JComboBox tecnico;
    private javax.swing.JLabel ti;
    private javax.swing.JComboBox tipo;
    private javax.swing.JLabel trat;
    private javax.swing.JComboBox tratamiento;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
